FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl wget
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate
EXPOSE 3001
CMD ["sh", "-c", "rm -rf dist && npx prisma migrate deploy 2>/dev/null; npx prisma db push --accept-data-loss 2>/dev/null; npm run dev"]
